modelServerPods:
  # Apply JSON patches to model server Pods so model caches are backed by PVC.
  jsonPatches:
    - op: add
      path: /spec/volumes/-
      value:
        name: hf-cache
        persistentVolumeClaim:
          claimName: kubeai-hf-cache
    - op: add
      path: /spec/containers/0/volumeMounts/-
      value:
        name: hf-cache
        mountPath: /root/.cache/huggingface
    - op: add
      path: /spec/volumes/-
      value:
        name: ollama-cache
        persistentVolumeClaim:
          claimName: kubeai-ollama-cache
    - op: add
      path: /spec/containers/0/volumeMounts/-
      value:
        name: ollama-cache
        mountPath: /root/.ollama

modelServerPersistentCache:
  enabled: true
  storageClassName: "nfs-rwx"
  accessModes:
    - ReadWriteMany
  hf:
    claimName: kubeai-hf-cache
    size: 80Gi
  ollama:
    claimName: kubeai-ollama-cache
    size: 80Gi

cacheProfiles:
  model-cache-80gb:
    sharedFilesystem:
      storageClassName: "nfs-rwx"
      size: "80Gi"
