apiVersion: v1
kind: Service
metadata:
  name: exaone-ollama
  namespace: kubeai
spec:
  selector:
    model: exaone3.5
  ports:
    - name: http
      port: 8000
      targetPort: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: exaone-ollama
  namespace: kubeai
  annotations:
    konghq.com/strip-path: "true"
spec:
  ingressClassName: kong
  rules:
    - http:
        paths:
          - path: /exaone
            pathType: Prefix
            backend:
              service:
                name: exaone-ollama
                port:
                  number: 8000
