apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-fss-pv
spec:
  storageClassName: "oci-fss"
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  csi:
    driver: fss.csi.oraclecloud.com
    volumeHandle: "ocid1.export.oc1.ap_chuncheon_1.aaaaaa4np2wfohzspfxhsllqojxwiotboawwg2dvnzrwqzlpnywtcllbmqwtcaaa:10.0.10.194:/oke_fss/grafana"
  mountOptions:
    - nosuid
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
