apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: airecipe-hpa
spec:
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
