imagePullSecrets: []

nameOverride: "langflow-service"
fullnameOverride: "langflow-service"

serviceAccount:
  create: true
  annotations: {}
  name: ""

ingress:
  enabled: false

securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
  allowPrivilegeEscalation: false
  runAsGroup: 1000

podSecurityContext:
  fsGroup: 1000
  runAsUser: 1000
  runAsNonRoot: true
  runAsGroup: 1000

langflow:
  global:
    image:
      tag: "latest"
  frontend:
    replicaCount: 1
    image:
      repository: docker.io/langflowai/langflow-frontend
      imagePullPolicy: IfNotPresent
      tag: latest
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 300m
        memory: 512Mi

  backend:
    replicaCount: 1
    service:
      type: ClusterIP
      port: 7860
    backendOnly: false
    numWorkers: 1
    image:
      repository: docker.io/bahn1075/langflow-custom
      imagePullPolicy: IfNotPresent
      tag: aarch64-20260509-1710
    command:
      - python
      - -m
      - langflow
      - run
      - --host
      - 0.0.0.0
    resources:
      requests:
        cpu: 100m
        memory: 1Gi
      limits:
        cpu: 500m
        memory: 3Gi
    probe:
      failureThreshold: 6
      periodSeconds: 10
      timeoutSeconds: 5
      initialDelaySeconds: 20
    autoLogin: false
    superuser: "admin"
    superuserPassword: "admin123"
    secretKey: "RuKHMArwWCAIeQbHuCJf3OAFP0rVoz2Gr7Lxx2gzkY8="
    env:
      - name: LANGFLOW_PORT
        value: "7860"
      - name: LANGFLOW_ALEMBIC_LOG_FILE
        value: "/app/db/alembic.log"
      - name: LANGFLOW_UPDATE_STARTER_PROJECTS
        value: "false"
      - name: LANGFLOW_MAX_FILE_SIZE_UPLOAD
        value: "100"
    nodeSelector: {}
    tolerations: []
    affinity: {}
    podAnnotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "9090"
      prometheus.io/path: "/metrics"

    securityContext:
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000
      allowPrivilegeEscalation: false
      runAsGroup: 1000

    podSecurityContext:
      fsGroup: 1000
      runAsUser: 1000
      runAsNonRoot: true
      runAsGroup: 1000

    externalDatabase:
      enabled: true
      driver:
        value: "postgresql"
      host:
        value: "postgresql.postgres.svc.cluster.local"
      port:
        value: "5432"
      user:
        value: "langflow"
      password:
        value: "langflow123"
      database:
        value: "langflow"

    volumes:
      - name: langflow-fss
        persistentVolumeClaim:
          claimName: langflow-fss-pvc
      - name: tmp
        emptyDir: {}

    volumeMounts:
      - name: langflow-fss
        mountPath: /app/flows
        subPath: langflow/flows
      - name: tmp
        mountPath: /tmp
        readOnly: false
      - name: langflow-fss
        mountPath: /app/data
        subPath: langflow/data
      - name: langflow-fss
        mountPath: /app/db
        subPath: langflow/db

    sqlite:
      enabled: false
      volume:
        size: "1Gi"
        existingStorageClassName: "default"
        storageClass: {}

secretProvider:
  enabled: false

postgresql:
  enabled: false
