controller:
  admin:
    username: "admin"
    existingSecret: "jenkins-admin-secret"

  ingress:
    enabled: true
    ingressClassName: nginx
    path: /
    pathType: Prefix
    hostName: jenkins.64bit.kr
    annotations: {}
    tls: []

  jenkinsUrl: "http://jenkins.64bit.kr"

persistence:
  enabled: true
  existingClaim: jenkins-fss-pvc
  subPath: jenkins

agent:
  resources:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      cpu: "1000m"
      memory: "1024Mi"
