apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: grafana
  labels:
    app: grafana
    environment: oci
spec:
  type: ClusterIP
  selector:
    app: grafana
    environment: oci
  ports:
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP
