apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-echo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/bahn1075/mykubernetes.git
    targetRevision: main
    path: minikube/demo/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
