apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale-operator
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: tailscale
  sources:
    - repoURL: https://pkgs.tailscale.com/helmcharts
      chart: tailscale-operator
      targetRevision: 1.98.9
      helm:
        releaseName: tailscale-operator
        valueFiles:
          - $values/helm/tailscale-operator/values.yaml
    - repoURL: https://github.com/bahn1075/mykubernetes.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/bahn1075/mykubernetes.git
      targetRevision: main
      path: helm/tailscale-operator/manifests/egress
  ignoreDifferences:
    - group: ""
      kind: Service
      jsonPointers:
        - /spec/externalName
        - /metadata/finalizers
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
