apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-model-fss-pvc
  namespace: ollama
  labels:
    app: ollama-model-fss-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
  volumeName: ollama-model-fss-pv
