apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://charts.konghq.com
      chart: ingress
      targetRevision: 0.22.0
      helm:
        valueFiles:
          - $values/helm/kong/values.yaml
    - repoURL: https://github.com/bahn1075/mykubernetes.git
      targetRevision: AI/desktop
      ref: values
    - repoURL: https://github.com/bahn1075/mykubernetes.git
      targetRevision: AI/desktop
      path: helm/kong/services
  destination:
    server: https://kubernetes.default.svc
    namespace: kong
  ignoreDifferences:
    - group: ""
      kind: Secret
      jsonPointers:
        - /data
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jqPathExpressions:
        - .webhooks[].clientConfig.caBundle
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
