# Kong ingress chart values (chart: kong/ingress 0.22.0)

controller:
  ingressController:
    gatewayDiscovery:
      enabled: true
      generateAdminApiService: true

gateway:
  admin:
    enabled: true
    type: LoadBalancer
    clusterIP: ""
    loadBalancerIP: 192.168.49.104
    http:
      enabled: true
    tls:
      enabled: true

  manager:
    enabled: true
    type: LoadBalancer
    loadBalancerIP: 192.168.49.103
    http:
      enabled: true
      servicePort: 80
    tls:
      enabled: false

  proxy:
    enabled: true
    type: LoadBalancer
    loadBalancerIP: 192.168.49.102

  env:
    role: traditional
    database: "off"
    admin_gui_url: "http://192.168.49.103"
    admin_gui_api_url: "http://192.168.49.104:8001"
